### ISSUE TITLE
Cannot find namespace 'java'

### ISSUE THREAD

**Issue by ghost** [yaqwsx/nativescript-simple-networking#1]
node_modules/nativescript-simple-networking/index.android.ts(5,34): error TS2503: Cannot find namespace 'java'.

node_modules/nativescript-simple-networking/index.android.ts(12,34): error TS2503: Cannot find namespace 'java'.

node_modules/nativescript-simple-networking/index.android.ts(21,31): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(22,36): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(43,36): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(47,34): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(48,32): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(49,45): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(55,34): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(56,32): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(57,45): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(65,30): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(66,36): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(67,35): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(116,33): error TS2304: Cannot find name 'java'.
node_modules/nativescript-simple-networking/index.android.ts(119,31): error TS2503: Cannot find namespace 'java'.
node_modules/nativescript-simple-networking/index.android.ts(201,33): error TS2304: Cannot find name 'java'.

**Comment by yaqwsx** [comment]
Can you provide more information about the problem (e.g. a sample project, where this problem occurs?).

**Comment by ghost** [comment]
tns create HelloWorld --template nativescript-template-ng-tutorial
tns plugin add nativescript-simple-networking

import {UdpServer, TcpClient, TcpServer} from "nativescript-simple-networking";
import {Address4} from "ip-address";

tns run android --emulator

co je špatně
what's wrong

**Comment by yaqwsx** [comment]
Something had to change in the recent update of the modules. I pushed a commit to the master branch, which resolves the problem for me. Could you please verify, it works in your configuration? If so, I will publish a new library version on NPM.

**Comment by ghost** [comment]
Thanks to Jan, everything works fine
Děkuji Jan, vše funguje
