### ISSUE TITLE
Could not find :SimpleNetworking:.

### ISSUE THREAD

**Issue by andreaboriani** [yaqwsx/nativescript-simple-networking#4]
When starting my app I get:

A problem occurred configuring root project
Could not resolve all dependencies for configuration ':_F0F1F2F3F4F5DebugApkCopy'
Could not find :SimpleNetworking:.
Required by:
project :

Any idea on how to solve it?

**Comment by yaqwsx** [comment]
I am sorry, but I am afraid I am not able to provide you a support. I am no NS develeper - I only used it once. Could you try as NS community for help? This seems like a more general NS problem and they should be able to provide you much better help.

**Comment by Buckwich** [comment]
I had the same problem. I fixed it by copying the [platform/android](https://github.com/yaqwsx/nativescript-simple-networking/tree/master/platforms/android) folder into my own project
